### ISSUE TITLE
Can you change the database to sqlite?

### ISSUE THREAD

**Issue by vkylamba** [seenureddy/galle-back#1]

**Comment by seenureddy** [comment]
Actually you need to add the  DATABASE_URL in the activation script of vitualenv. I changed the database settings to support for multiple database.

**Comment by vkylamba** [comment]
![screen shot 2016-08-09 at 12 42 38 pm 2](https://cloud.githubusercontent.com/assets/13446335/17507721/e9808a28-5e2e-11e6-9026-924b846f7e3f.png)

**Comment by seenureddy** [comment]
Here author is the ForeignKey to User Model. It's an raw id field you can click it and select the user. Then it wont give error. I gone with the more generic relations.

**Comment by vkylamba** [comment]
It does not show the selection list.

**Comment by vkylamba** [comment]
Just shows an empty text box. And if i put any username in it, it produces
error.

**Comment by seenureddy** [comment]
I'm uploading the screen shots from my system. It's taking the users from my system. Click search icon and click on the user name. Lemme know if you have any queries.

![screenshot from 2016-08-09 18 13 24](https://cloud.githubusercontent.com/assets/8179055/17516605/113da590-5e5d-11e6-8729-b4956cab2d99.png)
![screenshot from 2016-08-09 18 13 31](https://cloud.githubusercontent.com/assets/8179055/17516606/1175be80-5e5d-11e6-9627-630dcbd120bf.png)

**Comment by vkylamba** [comment]
I added two articles, by directly passing pk of the user in author text box. It did not show any user selection list. Now after adding the articles, the http://localhost/articles/ page does not show any article. I have attached the image. 
<img width="1280" alt="screen shot 2016-08-09 at 6 37 46 pm" src="https://cloud.githubusercontent.com/assets/13446335/17517355/b83047f6-5e60-11e6-8d9b-e822f7b4c0b1.png">
<img width="1280" alt="screen shot 2016-08-09 at 6 37 50 pm" src="https://cloud.githubusercontent.com/assets/13446335/17517354/b8302c62-5e60-11e6-8633-10a161a1f9c4.png">

**Comment by seenureddy** [comment]
Can you check it now ?

**Comment by vkylamba** [comment]
Okay, it worked.
